export const dummyPrompts = [
  {
    id: 1,
    title: "Instagram Carousel Generator",
    description: "Generate engaging Instagram carousels.",
    category: "Marketing",
    model: "GPT-5",
    author: "Alex Johnson",
    votes: 284,
    saves: 812,
    comments: 42,
    prompt: "Create a 10-slide Instagram carousel about {topic} with engaging hooks and CTA.",
  },
  {
    id: 2,
    title: "YouTube Script Writer",
    description: "Create viral YouTube scripts.",
    category: "Content",
    model: "Claude",
    author: "Sophia Lee",
    votes: 421,
    saves: 610,
    comments: 56,
    prompt: "Write an engaging YouTube script about {topic}.",
  },
  {
    id: 3,
    title: "Landing Page Copy",
    description: "High-converting landing page copy.",
    category: "Marketing",
    model: "GPT-5",
    author: "David Kim",
    votes: 612,
    saves: 1040,
    comments: 91,
    prompt: "Write persuasive landing page copy for {product}.",
  },
  {
    id: 4,
    title: "Logo Design Prompt",
    description: "Professional AI logo prompt.",
    category: "Design",
    model: "Midjourney",
    author: "Emma Brown",
    votes: 332,
    saves: 489,
    comments: 18,
    prompt: "Design a modern logo for {brand}.",
  },
  {
    id: 5,
    title: "React Dashboard",
    description: "Generate modern React dashboard.",
    category: "Coding",
    model: "GPT-5",
    author: "Michael Scott",
    votes: 790,
    saves: 1322,
    comments: 120,
    prompt: "Build a React admin dashboard using Tailwind CSS.",
  },
  {
    id: 6,
    title: "Business Plan Generator",
    description: "Startup business planning.",
    category: "Business",
    model: "Gemini",
    author: "Sarah Wilson",
    votes: 194,
    saves: 361,
    comments: 12,
    prompt: "Generate a complete startup business plan.",
  }
];